tier = "medium"

[shockingStrike]
name = "Shocking Strike"
description = "This enchantment is used only by the raid-bosses Tenebris, Banshee, Gatekeeper, and Power Mode Megalith. Currently has no known weapons that work with this enchantment, the game's Anti-Cheat instantly discards it."

[shockingStrike.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_SHOCK"

[lifesteal]
name = "Lifesteal"
description = """
A chance on every successful hit to replenish your health by 250% (100% for magic) of the damage dealt to the enemy. This chance depends on the power of the enchantment.
Available on Melee Weapons, Ranged Weapons and Magic.
"""

[lifesteal.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_LIFESTEAL_WEAPON"
ranged = "PERK_ITEM_SPECIAL_LIFESTEAL_RANGED"
magic = "PERK_ITEM_SPECIAL_LIFESTEAL_MAGIC"

[bleeding]
name = "Bleeding"
description = """
A chance that the enemy will start to lose 6% health (3.4% for magic) per second over 5 seconds after being hit. This chance is proportional to the damage dealt and the power of the enchantment.
Available on Melee Weapons, Ranged Weapons and Magic.
"""

[bleeding.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_BLEEDING_WEAPON"
ranged = "PERK_ITEM_SPECIAL_BLEEDING_RANGED"
magic = "PERK_ITEM_SPECIAL_BLEEDING_MAGIC"

[enfeeble]
name = "Enfeeble"
description = """
A chance to weaken your enemy's attacks by 75% for 10 seconds after a successful hit. This chance depends on the power of the enchantment.
Available on Melee Weapons, Ranged Weapons and Magic.
"""

[enfeeble.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_ENFEEBLE_WEAPON"
ranged = "PERK_ITEM_SPECIAL_ENFEEBLE_RANGED"
magic = "PERK_ITEM_SPECIAL_ENFEEBLE_MAGIC"

[frenzy]
name = "Frenzy"
description = """
A chance to increase your melee damage by 150% for 5 seconds after dealing or receiving a hit. This chance depends on the power of the enchantment.
Available on all types of equipment.
"""

[frenzy.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_FRENZY_WEAPON"
ranged = "PERK_ITEM_SPECIAL_FRENZY_RANGED"
magic = "PERK_ITEM_SPECIAL_FRENZY_MAGIC"
armor = "PERK_ITEM_SPECIAL_FRENZY_DEFENSE_ARMOR"
helm = "PERK_ITEM_SPECIAL_FRENZY_DEFENSE_HELM"

[stun]
name = "Stun"
description = """
A chance to stun your enemy for 3 seconds after a successful hit. This chance is proportional to the damage dealt and the power of the enchantment.
Available on Melee Weapons, Ranged Weapons and Magic.
"""

[stun.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_STUN_WEAPON"
ranged = "PERK_ITEM_SPECIAL_STUN_RANGED"
magic = "PERK_ITEM_SPECIAL_STUN_MAGIC"

["time_bomb"]
name = "Time Bomb"
description = """
A chance to set a time bomb on your enemy, which will detonate after 2 seconds. This chance depends on the power of the enchantment.
Available on Melee Weapons, Ranged Weapons and Magic.
"""

[time_bomb.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_TIME_BOMB_WEAPON"
ranged = "PERK_ITEM_SPECIAL_TIME_BOMB_RANGED"
magic = "PERK_ITEM_SPECIAL_TIME_BOMB_MAGIC"

[regeneration]
name = "Regeneration"
description = """
A chance to regenerate 4.5% of your health for 5 seconds after being hit. This chance is proportional to the damage dealt and the power of the enchantment.
"""

[regeneration.equipment_ids]
armor = "PERK_ITEM_SPECIAL_REGENERATION_ARMOR"
helm = "PERK_ITEM_SPECIAL_REGENERATION_HELM"

[shielding]
name = "Shielding"
description = """
A chance to reduce incoming damage by 75% for 7 seconds after being hit. This chance depends on the power of this enchantment.
"""

[shielding.equipment_ids]
armor = "PERK_ITEM_SPECIAL_SHIELDING_ARMOR"
helm = "PERK_ITEM_SPECIAL_SHIELDING_HELM"

[damage_return]
name = "Damage Return"
description = """
A chance on each hit that the enemy will take 85% of damage received. This chance depends on the power of the enchantment.
"""

[damage_return.equipment_ids]
armor = "PERK_ITEM_SPECIAL_DAMAGE_RETURN_ARMOR"
helm = "PERK_ITEM_SPECIAL_DAMAGE_RETURN_HELM"
