[Lifesteal]
weapon = "PERK_ITEM_SPECIAL_LIFESTEAL_WEAPON"
ranged = "PERK_ITEM_SPECIAL_LIFESTEAL_RANGED"
magic = "PERK_ITEM_SPECIAL_LIFESTEAL_MAGIC"

[Bleeding]
weapon = "PERK_ITEM_SPECIAL_BLEEDING_WEAPON"
ranged = "PERK_ITEM_SPECIAL_BLEEDING_RANGED"
magic = "PERK_ITEM_SPECIAL_BLEEDING_MAGIC"

[Enfeeble]
weapon = "PERK_ITEM_SPECIAL_ENFEEBLE_WEAPON"
ranged = "PERK_ITEM_SPECIAL_ENFEEBLE_RANGED"
magic = "PERK_ITEM_SPECIAL_ENFEEBLE_MAGIC"

[Frenzy]
weapon = "PERK_ITEM_SPECIAL_FRENZY_WEAPON"
ranged = "PERK_ITEM_SPECIAL_FRENZY_RANGED"
magic = "PERK_ITEM_SPECIAL_FRENZY_MAGIC"
armor = "PERK_ITEM_SPECIAL_FRENZY_DEFENSE_ARMOR"
helm = "PERK_ITEM_SPECIAL_FRENZY_DEFENSE_HELM"

[Stun]
weapon = "PERK_ITEM_SPECIAL_STUN_WEAPON"
ranged = "PERK_ITEM_SPECIAL_STUN_RANGED"
magic = "PERK_ITEM_SPECIAL_STUN_MAGIC"

["Time Bomb"]
weapon = "PERK_ITEM_SPECIAL_TIME_BOMB_WEAPON"
ranged = "PERK_ITEM_SPECIAL_TIME_BOMB_RANGED"
magic = "PERK_ITEM_SPECIAL_TIME_BOMB_MAGIC"

[Regeneration]
armor = "PERK_ITEM_SPECIAL_REGENERATION_ARMOR"
helm = "PERK_ITEM_SPECIAL_REGENERATION_HELM"

[Shielding]
armor = "PERK_ITEM_SPECIAL_SHIELDING_ARMOR"
helm = "PERK_ITEM_SPECIAL_SHIELDING_HELM"

["Damage Return"]
armor = "PERK_ITEM_SPECIAL_DAMAGE_RETURN_ARMOR"
helm = "PERK_ITEM_SPECIAL_DAMAGE_RETURN_HELM"
