["Stone Fetters"]
weapon = "PERK_DRAGON_SET_STONE"
ranged = "PERK_DRAGON_SET_STONE"
magic = "PERK_DRAGON_SET_STONE"
armor = "PERK_DRAGON_SET_STONE"
helm = "PERK_DRAGON_SET_STONE"

["Tempest Rage"]
weapon = "PERK_MONK_SET_WHIRL"
ranged = "PERK_MONK_SET_WHIRL"
magic = "PERK_MONK_SET_WHIRL"
armor = "PERK_MONK_SET_WHIRL"
helm = "PERK_MONK_SET_WHIRL"

["Typhoon Of Spirits"]
weapon = "PERK_SENTINEL_SET_SUPER_RETURN"
ranged = "PERK_SENTINEL_SET_SUPER_RETURN"
magic = "PERK_SENTINEL_SET_SUPER_RETURN"
armor = "PERK_SENTINEL_SET_SUPER_RETURN"
helm = "PERK_SENTINEL_SET_SUPER_RETURN"

["Arcane Martial Arts"]
weapon = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"
ranged = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"
magic = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"
armor = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"
helm = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"

["Time Shift"]
weapon = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"
ranged = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"
magic = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"
armor = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"
helm = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"

["Crimson Corruption"]
weapon = "PERK_WARLOCK_SET_CURSE"
ranged = "PERK_WARLOCK_SET_CURSE"
magic = "PERK_WARLOCK_SET_CURSE"
armor = "PERK_WARLOCK_SET_CURSE"
helm = "PERK_WARLOCK_SET_CURSE"

[Karma]
weapon = "PERK_SKANDA_SET_KARMA"
ranged = "PERK_SKANDA_SET_KARMA"
magic = "PERK_SKANDA_SET_KARMA"
armor = "PERK_SKANDA_SET_KARMA"
helm = "PERK_SKANDA_SET_KARMA"

["Icy Resistance"]
weapon = "PERK_GUARDIAN_SET_PROTECTION"
ranged = "PERK_GUARDIAN_SET_PROTECTION"
magic = "PERK_GUARDIAN_SET_PROTECTION"
armor = "PERK_GUARDIAN_SET_PROTECTION"
helm = "PERK_GUARDIAN_SET_PROTECTION"

["Plot Twist"]
weapon = "PERK_DIRECTOR_SET_PLOT_TWIST"
ranged = "PERK_DIRECTOR_SET_PLOT_TWIST"
magic = "PERK_DIRECTOR_SET_PLOT_TWIST"
armor = "PERK_DIRECTOR_SET_PLOT_TWIST"
helm = "PERK_DIRECTOR_SET_PLOT_TWIST"

[Squall]
weapon = "PERK_GUST_SET_WIND_MAKER"
ranged = "PERK_GUST_SET_WIND_MAKER"
magic = "PERK_GUST_SET_WIND_MAKER"
armor = "PERK_GUST_SET_WIND_MAKER"
helm = "PERK_GUST_SET_WIND_MAKER"

[Cordyceps]
weapon = "PERK_CORDYCEPS_FUNGUS_SET"
ranged = "PERK_CORDYCEPS_FUNGUS_SET"
magic = "PERK_CORDYCEPS_FUNGUS_SET"
armor = "PERK_CORDYCEPS_FUNGUS_SET"
helm = "PERK_CORDYCEPS_FUNGUS_SET"

["Roaring Luminary"]
weapon = "PERK_MAGMA_VOLCANO_SET"
ranged = "PERK_MAGMA_VOLCANO_SET"
magic = "PERK_MAGMA_VOLCANO_SET"
armor = "PERK_MAGMA_VOLCANO_SET"
helm = "PERK_MAGMA_VOLCANO_SET"

["Predator's Fury"]
weapon = "PERK_KARCER_HUNGER_SET"
ranged = "PERK_KARCER_HUNGER_SET"
magic = "PERK_KARCER_HUNGER_SET"
armor = "PERK_KARCER_HUNGER_SET"
helm = "PERK_KARCER_HUNGER_SET"
