[stone_fetters]
name = "Stone Fetters"
id = "PERK_DRAGON_SET_STONE"

[tempest_rage]
name = "Tempest Rage"
id = "PERK_MONK_SET_WHIRL"

[typhoon_of_spirits]
name = "Typhoon Of Spirits"
id = "PERK_SENTINEL_SET_SUPER_RETURN"

[arcane_martial_arts]
name = "Arcane Martial Arts"
id = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"

[time_shift]
name = "Time Shift"
id = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"

[crimson_corruption]
name = "Crimson Corruption"
id = "PERK_WARLOCK_SET_CURSE"

[karma]
name = "Karma"
id = "PERK_SKANDA_SET_KARMA"

[icy_resistance]
name = "Icy Resistance"
id = "PERK_GUARDIAN_SET_PROTECTION"

[plot_twist]
name = "Plot Twist"
id = "PERK_DIRECTOR_SET_PLOT_TWIST"

[squall]
name = "Squall"
id = "PERK_GUST_SET_WIND_MAKER"

[cordyceps]
name = "Cordyceps"
id = "PERK_CORDYCEPS_FUNGUS_SET"

[roaring_luminary]
name = "Roaring Luminary"
id = "PERK_MAGMA_VOLCANO_SET"

[predators_fury]
name = "Predator's Fury"
id = "PERK_KARCER_HUNGER_SET"
