[stoneFetters]
name = "Stone Fetters"
id = "PERK_DRAGON_SET_STONE"

[tempestRage]
name = "Tempest Rage"
id = "PERK_MONK_SET_WHIRL"

[typhoonOfSpirits]
name = "Typhoon Of Spirits"
id = "PERK_SENTINEL_SET_SUPER_RETURN"

[arcaneMartialArts]
name = "Arcane Martial Arts"
id = "PERK_ARCANE_MARTIAL_ART_SET_NEO_WANDERER"

[timeShift]
name = "Time Shift"
id = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"

[crimsonCorruption]
name = "Crimson Corruption"
id = "PERK_WARLOCK_SET_CURSE"

[karma]
name = "Karma"
id = "PERK_SKANDA_SET_KARMA"

[icyResistance]
name = "Icy Resistance"
id = "PERK_GUARDIAN_SET_PROTECTION"

[plotTwist]
name = "Plot Twist"
id = "PERK_DIRECTOR_SET_PLOT_TWIST"

[squall]
name = "Squall"
id = "PERK_GUST_SET_WIND_MAKER"

[cordyceps]
name = "Cordyceps"
id = "PERK_CORDYCEPS_FUNGUS_SET"

[roaringLuminary]
name = "Roaring Luminary"
id = "PERK_MAGMA_VOLCANO_SET"

[predatorsFury]
name = "Predator's Fury"
id = "PERK_KARCER_HUNGER_SET"
