# For the rest of perks
[invisibility]
name = "Invisibility"
id = "PERK_INVISIBILITY"
description = "Invisibility used by Lynx, Eclipse May and Fatum"

[hermitstorm]
name = "Hermit's Storm"
id = "PERK_HERMITSTORM"
description = "Hermit's boss ability"

[earthquake]
name = "Earthquake"
id = "PERK_EARTHQUAKE"
description = "Earthquake used by Butcher and Fungus"

[wasp_fly]
name = "Wasp Fly"
id = "PERK_WASPFLY"
description = "Flight ability used by Wasp"

[teleportation]
name = "Teleportation"
id = "PERK_TELEPORTATION"
description = "Teleportation used by Widow, Eclipse May and Volcano"

[assistants]
name = "Assistants"
id = "PERK_ASSISTANTS"
description = "Assistants used by Shogun"

[titans_shield]
name = "Titan's Shield"
id = "PERK_TITANS_SHIELD"
description = "Shield perk used by Titan"

[rat_wave]
name = "Rat Wave"
id = "PERK_RAT_WAVE"
description = "Rat wave used by Arkhos"

[hoaxen_tentacles]
name = "Hoaxen's Tentacles"
id = "PERK_HOAXEN_TENTACLES"
description = "Tentacles used by Hoaxen"

[hunger_claws]
name = "Hunger Claws"
id = "PERK_HUNGER_CLAWS"
description = "Ability used by Karcer"

[war_whirl]
name = "War Whirl"
id = "PERK_WAR_WHIRL"
description = "Ability used by Drakaina"

[power_field]
name = "Power Field"
id = "PERK_POWER_FIELD"
description = "Ability used by Gatekeeper"

[super_blaster]
name = "Super Blaster"
id = "PERK_SUPER_BLASTER"
description = "Super blaster used by Saturn"

[grasp_of_darkness]
name = "Grasp of Darkness"
id = "PERK_GRASP_OF_DARKNESS"
description = "Ability used by Blackness"

[hunterfly]
name = "Hunter Fly"
id = "PERK_HUNTERFLY"
description = "Flight ability used by Stalker"