[Precision]
weapon = "PERK_ITEM_SPECIAL_PRECISION_WEAPON"
ranged = "PERK_ITEM_SPECIAL_PRECISION_RANGED"
magic = "PERK_ITEM_SPECIAL_PRECISION_MAGIC"

[Overheat]
weapon = "PERK_ITEM_SPECIAL_OVERHEAT_WEAPON"
ranged = "PERK_ITEM_SPECIAL_OVERHEAT_RANGED"
magic = "PERK_ITEM_SPECIAL_OVERHEAT_MAGIC"
armor = "PERK_ITEM_SPECIAL_OVERHEAT_DEFENSE_ARMOR"
helm = "PERK_ITEM_SPECIAL_OVERHEAT_DEFENSE_HELM"

[Poisoning]
weapon = "PERK_ITEM_SPECIAL_INTOXICATION_WEAPON"
ranged = "PERK_ITEM_SPECIAL_INTOXICATION_RANGED"
magic = "PERK_ITEM_SPECIAL_INTOXICATION_MAGIC"

[Weakness]
weapon = "PERK_ITEM_SPECIAL_WEAKNESS_WEAPON"
ranged = "PERK_ITEM_SPECIAL_WEAKNESS_RANGED"
magic = "PERK_ITEM_SPECIAL_WEAKNESS_MAGIC"

["Magic Recharge"]
weapon = "PERK_ITEM_SPECIAL_MAGIC_DAMAGE_RECHARGE_WEAPON"
armor = "PERK_ITEM_SPECIAL_MAGIC_PAIN_RECHARGE_ARMOR"
helm = "PERK_ITEM_SPECIAL_MAGIC_PAIN_RECHARGE_HELM"

[Bloodrage]
weapon = "PERK_ITEM_SPECIAL_BLOODRAGE_WEAPON"
ranged = "PERK_ITEM_SPECIAL_BLOODRAGE_RANGED"
magic = "PERK_ITEM_SPECIAL_BLOODRAGE_MAGIC"

[Rejuvenation]
armor = "PERK_ITEM_SPECIAL_REJUVENATION_ARMOR"
helm = "PERK_ITEM_SPECIAL_REJUVENATION_HELM"

["Damage Absorption"]
armor = "PERK_ITEM_SPECIAL_DAMAGE_ABSORPTION_BODY_ARMOR"
helm = "PERK_ITEM_SPECIAL_DAMAGE_ABSORPTION_HEAD_HELM"
