# Unavailable Weapons
[WEAPON_HUNGER_SCYTHE]
name=""

[WEAPON_WAR_SHUANG_GOU]
name=""

[WEAPON_ELECTRO_BATONS]
name=""

[WEAPON_TRIANGLE_KNIVES]
name=""

[WEAPON_TWO_HANDED_SWORD]
name=""

[WEAPON_HEAVY_HAMMER]
name=""

[WEAPON_SENTINEL_KUSARIGAMA]
name=""

[WEAPON_BG_YARI]
name=""

[WEAPON_NODACHI]
name=""

[WEAPON_WAKIDZASHI]
name=""

[WEAPON_BG_NAGINATA]
name=""

[WEAPON_BG_GLAIVE]
name=""

[WEAPON_MERCENARY_CLAWS]
name=""

[WEAPON_MERCENARY_AXES]
name=""

[WEAPON_SAWBLADE]
name=""

[WEAPON_GIANT_SWORD]
name=""

[WEAPON_BATON]
name=""

[WEAPON_CRUSHER]
name=""

[WEAPON_DRAGON_KNIVES]
name=""

[WEAPON_TITAN_GIANT_SWORD]
name=""

[WEAPON_WAKIDZASHI-RangedBlade_1]
name=""

[WEAPON_RAVANA]
name=""

[WEAPON_MORGANA_SCYTHE]
name=""

[WEAPON_REAl_CLAWS]
name=""

[WEAPON_DEFAULT_RANDOM]
name=""

[WEAPON_DIRECTOR_HUNGER]
name=""

[WEAPON_LEVEL_RESTRICTION]
name=""

[WEAPON_RANDOM]
name=""

[WEAPON_SHOCKER_CLAWS_ARC]
name=""

[WEAPON_SUPER_BIG_SWORD]
name=""

[WEAPON_TITAN_SWORD]
name=""

[WEAPON_UNKNOWN]
name=""

[WEAPON_RAID_KARCER_SET]
name="Claws of Perversity"

[WEAPON_C3_z3]
name=""

[WEAPON_GLAIVE_25]
name="God Eater"

[WEAPON_HUNTER_CLAWS]
name=""

[WEAPON_NUNCHAKU_DANCEOFSTATIC_25]
name="Dance of Static"


# Unavailable Armors
[BODY_BRICK]
name=""

[BODY_CANDY]
name=""

[BODY_FEAR]
name=""

[BODY_HUNTER]
name=""

[BODY_INVISIBLE]
name=""

[BODY_KENJI]
name=""

[BODY_MONKEY]
name=""

[BODY_SCAVENGER_1]
name=""

[BODY_SCAVENGER_2]
name=""

[BODY_SCAVENGER_4]
name=""

[BODY_SHIN]
name=""

[BODY_SMOTHER]
name=""

[BODY_SON_OF_THE_SUN]
name=""

[BODY_TENTACLE_SKELETON]
name=""

[BODY_WOMAN]
name=""

[BODY_LYNX]
name=""

[BODY_BUTCHER]
name=""

[ARMOR_WASP]
name=""

[ARMOR_HUNTRESS]
name=""

[ARMOR_SHOGUN]
name=""

[BODY_FUTURE_MAY]
name=""

[BODY_TITAN]
name=""

[ARMOR_UNKNOWN]
name=""

[ARMOR_C3_z3]
name=""

[ARMOR_WOMAN_RONIN]
name=""

[ARMOR_WOMAN_LUMINOSITY]
name=""

[ARMOR_WOMAN_ALLOY]
name=""

[ARMOR_WOMAN_GREEN]
name=""

[ARMOR_WOMAN_REDSHIFT]
name=""

[ARMOR_WOMAN_BARBARIAN]
name=""

[ARMOR_BIG_BEAST_SHELL]
name=""

[ARMOR_BIG_CENTURION]
name=""

[ARMOR_BIG_QUILTED]
name=""

[ARMOR_BIG_SHROUD]
name=""

[ARMOR_BIG_SPIKE]
name=""

[ARMOR_REDSHIFT_BIG]
name=""

[ARMOR_XENOMORPH]
name=""

[ARMOR_LEVEL_RESTRICTION]
name=""

[ARMOR_EGYPT_25]
name="Scarab's Dream"

[ARMOR_RAID_KARCER_SET]
name="Legarthy"

[ARMOR_ZONE7_HERO1]
name=""

[ARMOR_ANCIENT]
name=""

[BODY_VULCAN]
name=""

[BODY_MEGALITH]
name=""

[BODY_FUNGUS]
name=""

[BODY_FISH]
name=""

[BODY_HUNGER]
name=""

[BODY_HOAXEN]
name=""

[BODY_WAR]
name=""

[BODY_GATEKEEPER]
name=""

[BODY_SATURN]
name=""

[BODY_RAVANA]
name=""

[BODY_WHISPER]
name=""


# Unavailable Helms
[HEAD_SCAVENGER_1]
name=""

[HEAD_SCAVENGER_2]
name=""

[HEAD_SCAVENGER_4]
name=""

[HEAD_SCAVEN]
name=""

[HEAD_DISCIPLE]
name=""

[HEAD_KENJI]
name=""

[HEAD_RAVANA]
name=""

[HEAD_SATURN]
name=""

[HEAD_MEPHISTO]
name=""

[HEAD_LYNX]
name=""

[HEAD_HERMIT]
name=""

[HEAD_BUTCHER]
name=""

[HEAD_RHINO]
name=""

[HEAD_WASP]
name=""

[HEAD_HUNTRESS]
name=""

[HEAD_TITAN]
name=""

[HEAD_SHROUD]
name=""

[HEAD_CYPHER]
name=""

[HEAD_ANCIENT]
name=""

[HEAD_CORSAIR]
name=""

[HEAD_FUTURE_MAY]
name=""

[HEAD_TITANS_ARMY1]
name=""

[HEAD_TITANS_ARMY2]
name=""

[HEAD_TITANS_ARMY3]
name=""

[HEAD_TITANS_ARMY4]
name=""

[HEAD_VULCAN]
name=""

[HEAD_MEGALITH]
name=""

[HEAD_FUNGUS]
name=""

[HEAD_FISH]
name=""

[HEAD_FATUM]
name=""

[HEAD_HOAXEN]
name=""

[HEAD_HUNGER]
name=""

[HEAD_WAR]
name=""

[HEAD_SATURN]
name=""

[HEAD_HUNTER]
name=""

[HEAD_ZONE7_HERO1]
name=""

[HEAD_ZONE7_HERO2]
name=""

[HEAD_ZONE7_HERO3]
name=""

[HEAD_BISON_V2]
name=""

[HEAD_BISON_SPIRIT]
name=""

[HEAD_CANDY]
name=""

[HEAD_NIGHT]
name=""

[HEAD_SMOTHER]
name=""

[HEAD_VILLAIN]
name=""

[HEAD_WHISPER]
name=""

[HEAD_MONKEY]
name=""

[HEAD_BRICK]
name=""

[HEAD_HYPERION]
name=""

[HEAD_INVISIBLE]
name=""

[HEAD_HIT]
name=""

[HEAD_HIT_ENEMY_REGENERATES]
name=""

[HEAD_C3_z3]
name=""

[HELM_LEVEL_RESTRICTION]
name=""

[HELM_UNKNOWN]
name=""

[HELM_AGNISSEAL]
name="Agni's Seal"

[HELM_RAID_KARCER_SET]
name="Comatosis"


# Unavailable Ranged Weapons
[RANGED_TITANS_HARPOON]
name=""

[RANGED_WAR_AXES]
name=""

[RANGED_FISH]
name=""

[RANGED_C3_z3]
name=""

[RANGED_LEVEL_RESTRICTION]
name=""

[RANGED_ONLY]
name=""

[RANGED_UNKNOWN]
name=""

[RANGED_BLASTER_ROGUESFORTUNE_25]
name="Rogue's Fortune"

[RANGED_RAID_KARCER_SET]
name="Snake Repear"


# Unavaiable Magic
[MAGIC_ICE_PINS]
name=""

[MAGIC_MIND_THROW]
name=""

[MAGIC_BUTCHER_EARTHQUAKE]
name=""

[MAGIC_ARCANE_BALL]
name=""

[MAGIC_ASTEROID-Node2]
name=""

[MAGIC_ASTEROID-Node4]
name=""

[MAGIC_C3_z3]
name=""

[MAGIC_HIT_BOX]
name=""

[MAGIC_HUNGER_CLAWS]
name=""

[MAGIC_LEVEL_RESTRICTION]
name=""

[MAGIC_MINE]
name=""

[MAGIC_RAT_WAVE]
name=""

[MAGIC_RESURRECTED_25]
name=""

[MAGIC_UNKNOWN]
name=""

[MAGIC_VERTICAL_TRIGGER]
name=""

[MAGIC_WAR_WHIRL]
name=""

[MAGIC_DARK_WAVE]
name=""

[MAGIC_ENERGY_BALL_PINK_25]
name="Thorn Dome"

[MAGIC_FEAR_RAY]
name=""

[MAGIC_ICE_BALL]
name=""

[MAGIC_PROJECTILE]
name=""

[MAGIC_GAZEOFTHEVOID_25]
name="Gaze of the Void"


