[WEAPON_TITAN_GIANT_SWORD]
name="Titan's Desolator"
description=""

[RANGED_TITANS_HARPOON]
name="Titan's Harpoon"
description=""

[MAGIC_MIND_THROW]
name="Mind Throw"
description=""

[BODY_TITAN]
name="Titan's Body"
description=""

[HEAD_TITAN]
name="Titan's Head"
description=""